server:
  port: 8082
spring:
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: order-service  # 服务名固定
  datasource:
    url: jdbc:mysql://mysql:3306/items-assigner?useSSL=false&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: Aa1341512355
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: MyHikariCP
  data:
    redis:
      host: redis
      port: 6379
      database: 3
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms
mybatis-plus:
  type-aliases-package: com.wddyxd.orderservice.pojo
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-server:10086/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
token:
  signKey: 123456
  expiration: 86400000
logging:
  config: classpath:logback-test.xml