server:
  port: 8082

spring:
  rabbitmq:
    host: localhost # RabbitMQ 服务地址
    port: 5672 # RabbitMQ 默认端口
    username: guest # 默认用户名（本地测试无需修改）
    password: guest # 默认密码（本地测试无需修改）
    virtual-host: / # 虚拟主机
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    template:
      mandatory: true
    connection-timeout: 3000 # 连接超时时间
    listener:
      simple:
        acknowledge-mode: auto # 自动确认消息（Demo场景简化配置，生产环境建议手动确认）
        concurrency: 5 # 消费者最小并发数
        max-concurrency: 10 # 消费者最大并发数
        prefetch: 1 # 每次从队列获取1条消息处理，避免消息堆积
        retry:
          enabled: true
          initial-interval: 1000
          max-interval: 30000
          multiplier: 1
          max-attempts: 5
          stateless: true #true则代表者处理一般消息,false则代表要处理事务消息
  datasource:
    url: jdbc:mysql://localhost:3306/items-assigner?useSSL=false&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: Aa1341512355
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: MyHikariCP
  application:
    name: order-service
  data:
    redis:
      host: localhost
      port: 6379
      database: 3
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8090
mybatis-plus:
  type-aliases-package: com.wddyxd.orderservice.pojo
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka/
token:
  signKey: 123456
  expiration: 86400000
logging:
  config: classpath:logback-dev.xml
feign:
  sentinel:
    enabled: true
seata:
  data-source-proxy-mode: AT
  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
    # 参考tc服务自己的registry.conf中的配置
    type: nacos
    nacos: # tc
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-server # tc服务在nacos中的服务名称
      cluster: default
  tx-service-group: items-assigner # 事务组，根据这个获取tc服务的cluster名称
  service:
    vgroup-mapping: # 事务组与TC服务cluster的映射关系
      items-assigner: default