server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.174.129:3306/items-assigner?useSSL=false&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: Aa1341512355
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: items-service
  data:
    redis:
      host: 192.168.174.129
      port: 6379
      database: 3
mybatis-plus:
  type-aliases-package: com.wddyxd.itemsservice.pojo
eureka:
  client:
    service-url:
      defaultZone: http://192.168.174.129:10086/eureka/
token:
  signKey: 123456
  expiration: 86400000