server:
  port: 8081
spring:
  application:
    name: items-service  # 服务名固定
  datasource:
    url: jdbc:mysql://mysql:3306/items-assigner?useSSL=false&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: Aa1341512355
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
      database: 3
mybatis-plus:
  type-aliases-package: com.wddyxd.itemsservice.pojo
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:10086/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
token:
  signKey: 123456
  expiration: 86400000