server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/items-assigner?useSSL=false&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: Aa1341512355
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: items-service
  data:
    redis:
      host: localhost
      port: 6379
      database: 3
mybatis-plus:
  type-aliases-package: com.wddyxd.itemsservice.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
token:
  signKey: 123456
  expiration: 86400000
logging:
  level:
    com.wddyxd.itemsservice: debug
    com.wddyxd.security: debug
    com.wddyxd.common: debug
  file:
    name: Log/items-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}.%method:%line - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}.%method:%line - %msg%n"
